### ISSUE TITLE
Add priors to priors.py

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#10]
Would be great to have more than one prior! Specifically, adding a uniform bounded prior and a linear prior (with parameters m, b of y=mx+b) (and any others you think might be useful) would be very helpful. For drawing samples from an arbitrary distribution, see: en.wikipedia.org/wiki/Inverse_transform_sampling.

**Comment by semaphoreP** [comment]
I added a lot of these in PR #26 but there's still the linear prior left to go. Let's try to finish this soon!

**Comment by sblunt** [comment]
Linear prior added in commit 27e72cff57d4d645356d45631d52cee9e41db518. I think we have all the v1.0 priors now!
