### ISSUE TITLE
autodoc not building

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#101]
The auto generated API pages for our docs don't seem to be working. This is most impactful for read input since the tutorial for read input just references the docstring: https://orbitize.readthedocs.io/en/latest/read_input.html

Seems like something is up with the readthedocs build system. The errors it's throwing for each auto generated page are along the lines of `WARNING: autodoc: failed to import module 'driver' from module 'orbitize'; the following exception was raised:` ... `AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'`, so something weird is going on.

**Comment by sblunt** [comment]
This should be fixed now. There were two issues: the webhook that tells readthedocs when to trigger a build stopped working, and I needed to point Sphinx to the correct docs location. I’m not sure why this was working before, but it should be fine now, and the webhook we’ve got now is good. Can you see the correct docs, Jason?

**Comment by semaphoreP** [comment]
Super, works now! Thanks for the quick and thorough investigation. I think they changed the webhook thing recently.
