### ISSUE TITLE
OFTI tutorial not showing up on readthedocs

### ISSUE THREAD

**Issue by isabelangelo** [sblunt/orbitize#102]
It looks like something is going wrong with the OFTI tutorial on readthedocs. I can look into it, I feel like it might just require someone re-adding it to github and pushing it to master.

**Comment by sblunt** [comment]
Oh no, more readthedocs issues! I will look into this too.

**Comment by sblunt** [comment]
I think this is happening because an extra parenthesis was added to the beginning of the jupyter notebook file in a recent commit (ff23515af5eee2ea6d5ccfbd4bb6c5891f90998b). I removed it and it seems to be fixed. Let's hope pushing to master builds the doc for this notebook properly.

**Comment by sblunt** [comment]
Ok, looks fixed to me now! I'm going to close this issue.

**Comment by isabelangelo** [comment]
looks good! It looks like that typo was mine, sorry about that!

**Comment by sblunt** [comment]
No problem!
