### ISSUE TITLE
``OFTI`` adds likelihood probability to ``results.py``, while ``MCMC`` adds posterior probability

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#103]
Just putting this minor bug here so I remind myself to address it. Currently, the OFTI sampler is adding likelihood probabilities (i.e. not multiplied by prior probabilities) to the ``Results`` object, and the MCMC sampler is adding posterior probabilities (i.e. with prior probabilities included). Not a big deal, and doesn't affect performance at all, but they should behave consistently.

**Comment by henry-ngo** [comment]
Which one would be more useful? Or any reason to keep both? My first thought is that posteriors are preferred since that's what determines which samples get chosen in the first place?

**Comment by semaphoreP** [comment]
Does the OFTI samples inherently have the prior probabilities in them, because they get drawn, weighted by the prior probability?

**Comment by sblunt** [comment]
Yes, prior probability is incorporated in how frequently various orbits are drawn, but the number OFTI currently returns is just -0.5*chi2. I guess it's just a matter of semantics, but that makes more sense to me as a likelihood. To calculate an a posteriori probability for a given OFTI orbit, you'd have to additionally incorporate the priors.

Maybe we could keep likelihood probability and prior probability separately? Having both won't increase the size of the save file toooo much, so perhaps that's justified. I agree that having the posterior probability is useful, but likelihood probability is nice too in case people want to report statistics about chi2, for example.

**Comment by sblunt** [comment]
The problem I'm facing now is that I want to look at chi2 for orbits run by OFTI and MCMC, and currently that requires treating OFTI and MCMC outputs differently.

**Comment by sblunt** [comment]
Does that make sense?

**Comment by semaphoreP** [comment]
Yes, I understand now! Basically our posteriors derived from the samples are consistent, but the reported probabilities correspond to different things. I agree that sounds like a good thing to keep straight. I think keeping both, or just keeping posterior probability are sensible solutions. In my experience, it doesn't take that much CPU time to recompute likelihood for chi2 if need be. I think either solution is good!

**Comment by henry-ngo** [comment]
Yeah, that makes a lot of sense! Thanks for the explanation / example of a use of the likelihood. In that case, I think it makes sense to have both likelihood and posterior (ptemcee/emcee provides both anyways). With knowledge of the prior, it's possible to get the posterior from just the likelihood or vice-versa, but more user-friendly to just have both!

**Comment by henry-ngo** [comment]
Ah, @semaphoreP said the same thing while I was typing :) Let me know if you want me to change the MCMC section of results.py or if you would rather just do both at the same time to keep things contained.

**Comment by sblunt** [comment]
Thanks @henry-ngo and @semaphoreP! Thanks for the offer Henry! I think this will be quick to patch up though, so I'll just do it all at once.

**Comment by sblunt** [comment]
I decided to just return the loglikelihood, rather than both it and the logprobability, since the results object code was getting messy with lots of try-except cases for backwards-compatibility. Users should be able to generate lnprobs without too much difficulty, and the code Junellie is working on (Issue #118) will make this more user-friendly too. Let me know what you think! See PR #126.

**Comment by sblunt** [comment]
Addressed in PR #126
