### ISSUE TITLE
Improvements to running long MCMC chains (restarting and saving)

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#104]
Have an argument that every so many steps, we save the current chains. This would be good for long MCMC runs so we can inspect the chains, or have their progress in case something crashes. 

A minor complication is whether we use the default Results save type, or whether we also need to expose the format of the saved chains in the MCMC API.

**Comment by semaphoreP** [comment]
We should also have it be able to restart from a current position.

**Comment by semaphoreP** [comment]
We should also do this for OFTI. Could be a separate issue.

**Comment by semaphoreP** [comment]
We should append to the HDF5 file rather than writing a completely new file (if possible).

**Comment by semaphoreP** [comment]
We should try to leverage the emcee v3 feature that does this.

**Comment by semaphoreP** [comment]
Note that ptemcee and emcee might need different solutions to this issue.

**Comment by semaphoreP** [comment]
We should make sure to have the ability to run the sampler, and then restart from where we left off if we call `run_sampler` again.

**Comment by sblunt** [comment]
Addressed in PR #217.
