### ISSUE TITLE
Error reporting for read_input

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#111]
After spending all day at the WFIRST data challenge with folks using orbitize, I've seen a few issues come up several times. I think they could be easily averted with more descriptive errors. The two bugs I saw several times today happened when:

- the path to the input csv was incorrect
- the input epochs were not in MJD

It would be great to add some error messages for these specific cases.

**Comment by sblunt** [comment]
Looks great. Thanks @henry-ngo. I purposefully didn't assign you to this issue because I didn't want to create more work for you but you were too quick!! :D I just added a message notifying the user that JD was changed to MJD. Let me know what you think of this addition, and I can pull the changes in.

**Comment by henry-ngo** [comment]
haha, I figure I should take ownership of read_input related issues :) Everything looks good!

**Comment by sblunt** [comment]
Addressed in PR #112
