### ISSUE TITLE
OFTI conversion of errors from RA/Dec to Sep/PA is incorrect

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#113]
The `radec2seppa` function can't be used to directly convert errors. See below (~line 126 in sampler.py). 
```
self.sep_err[i], self.pa_err[i] = radec2seppa(
                self.sep_err[i], self.pa_err[i]
            )
```
I think the error in separation should be the average error in RA and Dec, and the error in pa is sep_err/sep.

**Comment by sblunt** [comment]
Addressed in PR #126
