### ISSUE TITLE
Jeffrey's Prior should be renamed LogUniform Prior

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#114]
Because @semaphoreP and @jruffio are pedantic.

**Comment by rrubenza** [comment]
Made https://github.com/sblunt/orbitize/tree/mynameisjeff to make this small change

**Comment by rrubenza** [comment]
Done in #120

**Comment by sblunt** [comment]
(Note for posterity that we shouldn't close issues until the code has been pulled to master).

Thanks @rrubenza for taking this on!
