### ISSUE TITLE
Fitting RV measurements directly in orbitize!

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#115]
We want to eventually fit the RV measurements directly. This requires possibly 3 things:

 * Make sure all the hooks in orbitize are working to handle RV 
 * We should add the jitter of the star in the RV fit. This would involve sampling a new parameter (the RV jitter). 
 * Fitting for an RV offset/system RV

**Comment by sblunt** [comment]
Addressed in PR #146
