### ISSUE TITLE
Choose initial position of MCMC

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#116]
Currently walkers are started in positions that are uniformly drawn from the Prior space.

~Perhaps users can pass an argument specifying an initial guess for each parameter and a sigma value and we can draw walker positions from this distribution.~

~For more advanced users, we should have a convenience function that lets users create their own list of start positions and then update `sampler.curr_pos` with this list.~

Decided to write a tutorial on how to modify this instead, for now.

**Comment by sblunt** [comment]
Addressed in PR #124
