### ISSUE TITLE
Default behavior for restrict_angle_ranges

### ISSUE THREAD

**Issue by jruffio** [sblunt/orbitize#117]
For its default behavior, it looks like the intent of the code is to set the restrict_angle_ranges  flag based on the dimensions of the input data (although it is not described in the docstring). However, I think this is currently not working:

The line 

> if (len(radec_indices) + len(seppa_indices) == len(self.data_table)) and (restrict_angle_ranges is None):

should be replaced by

> if (len(radec_indices[0]) + len(seppa_indices[0]) == len(self.data_table)) and (restrict_angle_ranges is None):

**Comment by sblunt** [comment]
Thanks JB. I decided to remove these lines of code after all. I'll let the user/sampler object decide when to restrict the angle ranges.

**Comment by sblunt** [comment]
See PR #126

**Comment by sblunt** [comment]
We actually ended up addressing this issue in PR #131.

**Comment by sblunt** [comment]
Re-removed in PR #126
