### ISSUE TITLE
Tutorial for including RV measurements

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#127]
Once the RV+astrometry implementation is finalized, we should add a tutorial. This should show how to do a joint fit, show how to read in RadVel posteriors as priors, and discuss when each option is appropriate.

**Comment by aburgasser** [comment]
Hi everyone, checking to see if there is any progress on this; I'd like to try using orbitize for *stellar* binaries using RV measurements alone, but am having trouble figuring out how to set up the system/driver for this

**Comment by sblunt** [comment]
Hi Adam! Excited to hear that you’re using orbitize!

We’re still putting the finishing touches on the RV+astrometry implementation. Those involved are taking finals and writing grad apps right now, so expect an update in a few weeks.

**Comment by sblunt** [comment]
Addressed in PR #146
