### ISSUE TITLE
Save orbitize version to results

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#129]
This is probably good for legacy recording and sanity checking purposes. We should save the orbitize version number, and perhaps even the git commit version (although would not exist if installed from pip). Sometimes I don't remember which version of orbitize I used for a fit, and it may not matter now, but it could matter in the future.

**Comment by henry-ngo** [comment]
I like this. I think we can just use version number as long as we are consistent about incrementing version number whenever a major change in how a fit happens or a bugfix is merged onto (into?) master.

**Comment by semaphoreP** [comment]
Yeah, I think the version number is probably good enough. We have been good about updating version numbers frequently, and if we continue to do so, that should be fine.

**Comment by sblunt** [comment]
Addressed in PR #218. Thanks @hgallamore!
