### ISSUE TITLE
Support for Python2 beyond Jan 1 2020

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#132]
I believe that we have decided that we'll support Python2 for as long as it does not require too much extra effort to maintain. Some scientific python packages have already dropped Python2 support and [many more have pledged to drop it by Jan 1, 2020](https://python3statement.org/). 

After Jan 1, 2020, orbitize might unexpectedly stop working in Python2 so we should print a warning message to this effect in an upcoming release! It would also be a good idea to encourage migration to Python3. 

Perhaps a good place to print the message is upon package import if we detect the user is running Python2.

This issue is related to #128 .

**Comment by r0cketr1kky** [comment]
Has anyone started working on this? Can you assign me this task, if it hasn't been taken up already @semaphoreP?

**Comment by sblunt** [comment]
Hey @r0cketr1kky, sorry we missed your earlier comment. There wasn't anything to do for this issue, it was mainly just a reminder for us to think about when we should drop support for Python 2. We're decided to make good on that promise in PR #157.
