### ISSUE TITLE
OFTI doesn't handle PAN priors properly

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#144]
While working with someone on an OFTI fit who was trying to limit the range of PAN, they noticed that OFTI still produced samples outside of the prior bounds. This is because OFTI scale and rotate and rotate PAN to be outside of the bounds, but does not check for it.

**Comment by sblunt** [comment]
Good point. I did this intentionally but did not print an error/warning message. I have added the ability to set priors on pan in the RV posts as priors branch, so I will fix this at latest when I pull that code in.

**Comment by sblunt** [comment]
Partially addressed in PR #186. Still need to implement the ability to apply arbitrary PAN priors in OFTI

**Comment by sblunt** [comment]
Finally fixed in PR #245
