### ISSUE TITLE
Handle covariances in measured astrometry

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#150]
Sometimes, RA/Dec and Sep/PA are not the principal axes of the error ellipse and we instead need to handle error covariances. We need to include new API/formatting in read_input to deal with covariances. Is this something we want to fully implement in the code base, or leave to the custom likelihood function?

**Comment by semaphoreP** [comment]
I've been getting some demand for this so I might try to add it after multiplanet. I think the biggest thing is that we need to add another column to the Table that is returned by `read_input`. We would basically need a column that's "cov12" that gives the covariance between quant1 and quant2. With that and `quant1_err` and `quant2_err`, we can reconstruct the 2x2 covariance matrix and use it in the likelihood. 

I was wondering if @henry-ngo has any ideas for the best way to implement this. I have thought of two ideas:
1. Always have the column `cov12`, and the sampler.py code will check if the column is all zeros or not (if not, it needs to tell the likelihood to properly handle it).
2. The column `cov12` only appears if the user passes in some ascii data that has that column. sampler.py code will check if the column exists, and if it does, it will need to tell the likelihood to properly handle it.

I'm leaning towards the first option, even though at first-glance it appears to be less elegant, as the output table is still small and it keeps the output of read_input straightforward with less edge cases.

**Comment by sblunt** [comment]
Addressed in PR #209. Thanks @semaphoreP!
