### ISSUE TITLE
Minor issues for developers

### ISSUE THREAD

**Issue by aryadas98** [sblunt/orbitize#153]
There are some minor documentation issues for developers.
- Installation instruction for developers does not work in a fresh environment because numpy is not installed. Workaround is to install dependencies using `pip install -r requirements.txt` first.
- Cython and pytest are not listed in the requirements.
- In the quickstart guide, the file `GJ504.csv` cannot be located by `'{}/GJ504.csv'.format(orbitize.DATADIR)` if orbitize is installed using `python setup.py develop`.

**Comment by sblunt** [comment]
Addressed in PR #157

**Comment by semaphoreP** [comment]
I don't think we addressed these issues, so I'm going to re-open this to remind us to update documentation.

**Comment by sblunt** [comment]
I updated the documentation. Do you not see the changes? Maybe there's an issue with the docs...

**Comment by semaphoreP** [comment]
Ah my bad! I didn't see you updated the documentation.
