### ISSUE TITLE
Add omega/Omega documentation

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#158]
Brendan Bowler suggested we add some more explicit documentation about the relationship between tau/orbital period/EPP and the geometric interpretation of omega/Omega. I’d also like to add something explaining the geometric inclination prior since that’s a question I get asked a lot.

**Comment by semaphoreP** [comment]
related to issue #106 also

**Comment by sblunt** [comment]
Add to FAQ section.

**Comment by sblunt** [comment]
Addressed in PR #267
