### ISSUE TITLE
Xcode download

### ISSUE THREAD

**Issue by zhexingli** [sblunt/orbitize#159]
I had orbitize before but uninstalled it along with xcode due to my software issues. Now I want to get it back, but the latest Xcode in the current Apple app store saying my version of Mac OS is too old (10.14.3) and the system needs to be at least 10.14.4 to be able to downloand Xcode. I don't want to upgrade my system to Catalina because of the a lot of software incapatibility issues other people are complaining. Is there a way to download older version of Xcode?

**Comment by sblunt** [comment]
Hey Zhexing! You can download older versions of Xcode by following the steps listed in the top voted answer to this stackoverflow question: https://stackoverflow.com/questions/7047735/where-can-i-download-old-versions-of-xcode

Hope that helps!

**Comment by zhexingli** [comment]
Thx Sarah!
