### ISSUE TITLE
MCMC examine_chains() should have a transparency option

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#163]
We plotting more than 10 chains, or very long chains, the walker plots generated by `mcmc.examine_chains()` are hard to read if we don't have transparency enabled. Example below:

![image](https://user-images.githubusercontent.com/2245740/77560736-13c60a00-6e7b-11ea-9516-ec1f6da282ee.png)

Transparency will help us better have a sense of the density of walkers, which otherwise we can't tell. We can make it an optional user argument to tune the level of transparency.

**Comment by sblunt** [comment]
Addressed in PR #183
