### ISSUE TITLE
Make the Kepler equation solver faster

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#17]
We can probably use `cython` to make the iterative solver for eccentric anomaly faster. It should check though if `cython` is supported on the user machine, and default back to the python solver if needed.

**Comment by sblunt** [comment]
@devincody another thing you could work on is eliminating the `for` loops in `orbitize.kepler.calc_orbit()` using 2d array indexing.

**Comment by sblunt** [comment]
Just kidding about that last comment. Henry is working on it!

**Comment by sblunt** [comment]
Addressed in PR #46.
