### ISSUE TITLE
Python 3.8 MacOS Parallelism Issue?

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#174]
It's unclear right now if this affects all Macs running python 3.8 or some very specific setup. Regardless, running the basic OFTI tutorial (e.g., from issue #171) returns the following cryptic multiprocessing bug in OFTI:

```
Exception has occurred: RuntimeError
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "/Users/user/codeastro/orbitize/orbitize/sampler.py", line 334, in run_sampler
    manager = mp.Manager()
  File "/Users/user/codeastro/Day2/broken_orbitize.py", line 7, in <module>
    s.run_sampler(1000)
```

**Comment by Steelhead86** [comment]
This does not appear to be a MacOS specific issue, as I am currently encountering it on Windows 10.
If it's helpful:
`python3 --version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]`

**Comment by ShirleneLiu** [comment]
I met the similar problem with Python version 3.8 when training PyTorch DCGAN through terminal(https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html). However it didn't go wrong in IPython of Jupyter notebook. I can't understand why even if I read python docs 😶

As a result I only solved it as follows:

> from multiprocessing import freeze_support
> def train():
>     ......
> if name == 'main':
>     freeze_support()
>     train()

**Comment by ShirleneLiu** [comment]
macOS / Python3.8

I met the similar problem when I trained PyTorch DCGAN through terminal(https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html). However it didn't go wrong in IPython of Jupyter notebook. I can't understand why even if I read python docs 😶, on it there only mentioned Windows would encounter with this 'RuntimError'

As a result I had to solve it as follows:
`
from multiprocessing import freeze_support
def train():
    ......
if __name__ == '__main__':
    freeze_support()
    train()
`

**Comment by ShirleneLiu** [comment]
Additional remarks.
I found the source problem where I set dataloader argument 'num_workers=2'.  
https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader
```python
num_workers  (int, optional) – how many subprocesses to use for data loading. 0 means that the data will be loaded in the main process. (default: 0) 
```

**Comment by sblunt** [comment]
Sweet, thanks so much! Would you be willing to PR this change?

**Comment by sblunt** [comment]
I just confirmed that I can run the OFTI tutorial in jupyter using a python 3.8 kernel, as well as the test_OFTI.py script from the command line using a python 3.8 kernel. Both use the multiprocessing code, so that means I am unable to replicate this bug. I tried this on my mac (running Big Sur) and on a linux machine, and both worked. Closing for now. Please reopen if anyone runs into this again.
