### ISSUE TITLE
sampler.curr_pos and results.post would benefit from a dictionary like system.param_idx too

### ISSUE THREAD

**Issue by sylacour** [sblunt/orbitize#177]
I like to force priors to a given value, and/or insert new priors thanks to the custom_lnlike function.

However, I have difficulties using the same code because the length of the array for curr_pos (before running the MCMC) and results.post (after running MCMC) keep changing.

I know there is a results.labels array, but it does not look like it is properly updated to additional prior.

Could it be possible to add a dictionary like system.param_idx and to both the results and sampler class?

Thanks!
Sylvestre

**Comment by semaphoreP** [comment]
Sure. Good suggestion. I'll note that inserting new priors is not "officially" supported in orbitize yet, so we need to build a lot of that infrastructure still. However, having a dictionary for the MCMC sampler length changing due to fixed parameters makes sense to me.

**Comment by sblunt** [comment]
I think it might be a good idea to move towards pandas dataframes rather than arrays of parameters and lists of labels.

**Comment by sblunt** [comment]
This has been added in PR #212. Sylvestre, when you have a chance please test out the new code and let us know if it fits with your suggestion. I'll wait to pull it into main until you confirm.

**Comment by sblunt** [comment]
Addressed in PR #212
