### ISSUE TITLE
tau_ref_epoch inconsistency

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#182]
The default value for `tau_ref_epoch` in `kepler.calc_orbit` is 0, while in the rest of the package, `tau_ref_epoch` is at `58849`. This is technically a breaking change in case other people are calling calc_orbit assuming tau_ref_epoch=0 works for them, but that subset of orbitize users may just be me.. (but nevertheless, we should document the change in the release notes).

**Comment by sblunt** [comment]
Addressed in PR #187
