### ISSUE TITLE
ptemcee 'ntemps' keyword TypeError

### ISSUE THREAD

**Issue by wbalmer** [sblunt/orbitize#190]
First ran into this error trying to fit my own data, but in attempting to run the [MCMC Introduction tutorial](http://orbitize.info/en/latest/tutorials/MCMC_tutorial.html)  with GJ504 I get the same error. My installations of ptemcee and orbitize are both current, and I'm working on python 3.8.5 on a Windows machine.

import orbitize
from orbitize import driver
import multiprocessing as mp

filename = "{}/GJ504.csv".format(orbitize.DATADIR)

num_secondary_bodies = 1
system_mass = 1.75 # [Msol]
plx = 51.44 # [mas]
mass_err = 0.05 # [Msol]
plx_err = 0.12 # [mas]

num_temps = 5
num_walkers = 20
num_threads = mp.cpu_count() # or a different number if you prefer

my_driver = driver.Driver(
    filename, 'MCMC', num_secondary_bodies, system_mass, plx, mass_err=mass_err, plx_err=plx_err,
    mcmc_kwargs={'num_temps': num_temps, 'num_walkers': num_walkers, 'num_threads': num_threads}
)

total_orbits = 6000 # number of steps x number of walkers (at lowest temperature)
burn_steps = 10 # steps to burn in per walker
thin = 2 # only save every 2nd step

my_driver.sampler.run_sampler(total_orbits, burn_steps=burn_steps, thin=thin)`

TypeError                                 Traceback (most recent call last)
<ipython-input-4-4a9ba92a00ae> in <module>
     23 thin = 2 # only save every 2nd step
     24 
---> 25 my_driver.sampler.run_sampler(total_orbits, burn_steps=burn_steps, thin=thin)

c:\users\willi\amherst\thesis\code\orbitize\orbitize\sampler.py in run_sampler(self, total_orbits, burn_steps, thin, examine_chains)
    641 
    642         if self.use_pt:
--> 643             sampler = ptemcee.Sampler(
    644                 self.num_walkers, self.num_params, self._logl, orbitize.priors.all_lnpriors,
    645                 ntemps=self.num_temps, threads=self.num_threads, logpargs=[self.priors, ]

TypeError: __init__() got an unexpected keyword argument 'ntemps'

**Comment by wbalmer** [comment]
Appears to be a windows specific error, I could run the tutorial on a lab mac

**Comment by sblunt** [comment]
Hey William,

Thanks for the bug report. Does the issue persist if you downgrade to Python 3.7?

**Comment by wbalmer** [comment]
Hey Sarah, it appears that it persists after downgrading to 3.7.9. I started a fresh conda env with python 3.7 and only the required orbitize/jupyter notebook dependencies (sorry, forgot to mention I'm working out of a notebook, but I just put the same code into a script and got the same error). 

Here's the result:

my_driver.sampler.run_sampler(total_orbits, burn_steps=burn_steps, thin=thin)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6af5f37e1b34> in <module>
      4 thin = 1 # only save every 2nd step
      5 
----> 6 my_driver.sampler.run_sampler(total_orbits, burn_steps=burn_steps, thin=thin)

c:\users\willi\amherst\thesis\code\orbitize\orbitize\sampler.py in run_sampler(self, total_orbits, burn_steps, thin, examine_chains)
    643             sampler = ptemcee.Sampler(
    644                 self.num_walkers, self.num_params, self._logl, orbitize.priors.all_lnpriors,
--> 645                 ntemps=self.num_temps, threads=self.num_threads, logpargs=[self.priors, ]
    646             )
    647         else:

TypeError: __init__() got an unexpected keyword argument 'ntemps'

from platform import python_version

print(python_version())

3.7.9

**Comment by sblunt** [comment]
Hey William, 

One more thought-- I believe that the ``ptemcee`` implementation on GitHub is different that the version on pypi. How did you install ``ptemcee``?

**Comment by wbalmer** [comment]
I installed `ptemcee` by cloning the github and running a "pip install -e ." command, same with `orbitize`. The last time I checked, this was how I had to install it on windows to avoid some error that occured when running "pip install orbitize"

**Comment by sblunt** [comment]
Ah I see. Can you try downloading and installing from [the pypi page instead](https://pypi.org/project/ptemcee/#modal-close)? If that fixes the issue, I'll update the documentation so future users don't run into this problem.

**Comment by wbalmer** [comment]
Downloading the file from pypi throws the same issue as "pip install orbitize", same as "pip install ptemcee"

C:\Users\willi\Amherst\Thesis\Code\ptemcee-1.0.0>pip install -e .
Obtaining file:///C:/Users/willi/Amherst/Thesis/Code/ptemcee-1.0.0
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\willi\\Amherst\\Thesis\\Code\\ptemcee-1.0.0\\setup.py'"'"'; __file__='"'"'C:\\Users\\willi\\Amherst\\Thesis\\Code\\ptemcee-1.0.0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\willi\AppData\Local\Temp\pip-pip-egg-info-d9linv2j'
         cwd: C:\Users\willi\Amherst\Thesis\Code\ptemcee-1.0.0\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\willi\Amherst\Thesis\Code\ptemcee-1.0.0\setup.py", line 39, in <module>
        long_description=read('README.rst'),
      File "C:\Users\willi\Amherst\Thesis\Code\ptemcee-1.0.0\setup.py", line 20, in read
        return f.read()
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 449: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sblunt** [comment]
Sorry. You'd have to make the same change (removing the README) before attempting to reinstall.

**Comment by wbalmer** [comment]
That does it. It appears the issue is particularly their use of the characters in their pronounciation of "'tɛmsi" in their readme, I deleted that line and didn't have to remove the README. 

After downloading from the pypi page, removing that line, running pip install -e . to install ptemcee, and then running pip install orbitize, the code runs without the 'ntemps' keyword error. Sorry about all the trouble, thanks for your help!

**Comment by sblunt** [comment]
Awesome, thanks for raising this issue William!
