### ISSUE TITLE
Implement PTMCMC Sampler

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#2]
Get it working for a 1 planet, imaging-only dataset

**Comment by henry-ngo** [comment]
As I wrote in the Slack channel, there's a package out there by Olivier Wertz that does an MCMC orbit fit. (https://github.com/vortex-exoplanet/PyAstrOFit). Worth taking a look to see how it compares with @semaphoreP module and whether there's stuff worth adding and/or implementing O. Wertz's code as a separate sampler (Olivier Absil mentioned this to me and that Wertz would probably be willing to contribute, so once we get our this samplers started, probably a good idea to see if he would want to add his sampler, if it's different enough).

**Comment by semaphoreP** [comment]
I skimmed over it and it just looks like it uses the emcee affine invariant sampler, with a GR metric for figuring out when it would stop. I'm not sure this is significantly different than what I was going to do: basically a wrapper for emcee's parallel tempered affine invariant sampler. Basically, I think either way it's just a wrapper to the emcee package, so I don't think it would be too different.

**Comment by semaphoreP** [comment]
Implemented a version in PR #26. Let's close this issue and open up bugs on it as new issues.
