### ISSUE TITLE
Speed up `numpy` implementation of `kepler.py`

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#20]
- turn `for` loops into vector array operations

**Comment by henry-ngo** [comment]
I was just reviewing this too. I think we have already addressed the main point in the issue awhile ago (turn for loops in vector ops). But last week Rob mentioned another big speedup if we pass `manom` as an array. I think that is good but it does break some parts of the code, which I'm discussing with him on Slack now in a thread from his comment.

So I think we can keep this issue open until we resolve that.

**Comment by sblunt** [comment]
Ok, sounds good.

**Comment by sblunt** [comment]
Addressed in PR #58
