### ISSUE TITLE
Backwards compatability with v1.14 and v.15 features

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#219]
Some new features currently don't work with old versions of orbitize data products (input astrometry/results files). 

  * not having `quant12_corr` or `instrument` in an orbitize data file (the ones with `quant_type` as a field)
  * not having an orbitize version in the results file

We should add some default options to handle missing cases.

**Comment by wbalmer** [comment]
have been loading a hdf5 results file using loaded_results.load_results(hdf5_filename) (file attached) and loaded_results.data is None. Should I revert to 1.14?

[my_posterior_lab.zip](https://github.com/sblunt/orbitize/files/6213994/my_posterior_lab.zip)

**Comment by semaphoreP** [comment]
@wbalmer Hmm.. this seems like a bug. I'm not sure if reverting to a old version will fix it since it's a relatively new feature. Are you trying to access the input astrometry? Probably the suggested workaround is to read in the input astrometry again with `read_input` in your code.

**Comment by wbalmer** [comment]
@semaphoreP Sorry, I realize now I misread and this issue was about the input astrometry, so I opened a separate issue #221 . I'm trying to access the posterior that I had saved previously, the problem seems to be that the results file I had saved doesn't have a version number.

**Comment by semaphoreP** [comment]
@wbalmer Oh no, you were right in interpreting this issue was with the version number! I just misread your comment. I just opened PR #222 to fix the version backwards compatibility issue. Feel free to copy that code or use that branch if you need this to work before we release a new version of orbitize.

**Comment by semaphoreP** [comment]
I'll add that it seems like perhaps the results.data being None is a separate bug. We'll take a closer look!

**Comment by semaphoreP** [comment]
It looks like results.data is being populated for me. @wbalmer, if you still have this problem, can you re-open #223 and point us to a script to reproduce?
