### ISSUE TITLE
advanced plotting tutorial outdated to new .plot_orbits axes

### ISSUE THREAD

**Issue by wbalmer** [sblunt/orbitize#220]
Small thing, but I had been using the method in the advanced plotting tutorial to zoom in on the sep+pa plots and ran into this error after updating to the [current commit](https://github.com/sblunt/orbitize/commit/7dd37f690627556b28c107595b046e8b2363027a). The documentation gives 

epochs = my_driver.system.data_table['epoch']

orb_fig = loaded_results.plot_orbits(
    object_to_plot = 1, # Plot orbits for the first (and only, in this case) companion
    num_orbits_to_plot= 100, # Will plot 100 randomly selected orbits of this companion
    start_mjd=epochs[0] # Minimum MJD for colorbar (here we choose first data epoch)
)

ax_orb, ax_cbar, ax_sep, ax_pa  = orb_fig.axes

...

ax_sep.set_xlim(arbitrary zoom)
ax_pa.set_xlim(arbitrary zoom)
ax_sep.set_ylim(arbitrary zoom)
ax_pa.set_ylim(arbitrary zoom)

but the current orb_fig.axes returns in the order ax_orb, ax_sep, ax_pa, ax_cbar (I think)

so running an old script with the old visualization gives an error 
`ValueError: Image size of 2134x78302 pixels is too large. It must be less than 2^16 in each direction.`

because it assigns the colorbar axes to the pa axes and zooms way to far out creating a gigantic colorbar. Took me a moment to puzzle out

**Comment by sblunt** [comment]
Wonderful, a bug report and solution in one issue. Thanks @wbalmer!

**Comment by sblunt** [comment]
Addressed in PR #224
