### ISSUE TITLE
results.Results.load_results backwards compatibility issue with v1.15 - Can't open attribute (can't locate attribute: 'version_number')

### ISSUE THREAD

**Issue by wbalmer** [sblunt/orbitize#221]
I had saved the posterior running the code below on a previous version of orbitize (I think 1.13?):

hdf5_filename='my_posterior_lab.hdf5'
import os
if os.path.isfile(hdf5_filename):
    os.remove(hdf5_filename)
my_driver.sampler.results.save_results(hdf5_filename)

and tried to load it on the current version 1.15 using:

hdf5_filename='my_posterior_lab.hdf5'
from orbitize import results
loaded_results = results.Results() 
loaded_results.load_results(hdf5_filename)

which previously loaded the results but now gives the error:
`KeyError: "Can't open attribute (can't locate attribute: 'version_number')"`

I uploaded the file I was trying to load: https://github.com/sblunt/orbitize/files/6213994/my_posterior_lab.zip

Is there a way to salvage this posterior I had saved?

**Comment by sblunt** [comment]
Addressed in PR #222.
