### ISSUE TITLE
Make plotting robust against super long periods

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#241]
If we have periods > 10^9 days, the `epochs` array of `results.plot_orbit` is unable to convert from MJD to decimal error due to an issue with `astropy.time`. This is so far in the future that we should catch this error and limit the colorbar to be between some reasonable dates. 

Reproduction:
Run the RV MCMC Tutorial Notebook and the plot_orbit will throw an error because we have some really long periods.

**Comment by sblunt** [comment]
Jason notes that this only in the colorbar epoch conversion. See his suggestion above.

**Comment by sblunt** [comment]
Addressed in PR #276
