### ISSUE TITLE
"Converting ra/dec data points in data_table to sep/pa" not occurring in MCMC fitting?

### ISSUE THREAD

**Issue by rbowru** [sblunt/orbitize#252]
Hello! 

I am using an input file with mixed ra/dec and sep/pa points.  When using OFTI, the message "Converting ra/dec data points in data_table to sep/pa" appears and the data points are converted correctly.  When using MCMC, this message does not appear and the data conversion does not appear to be happening.  

I've included a couple of screenshots.  Thank you! 

![OFTI](https://user-images.githubusercontent.com/66432460/129112025-459c7e86-54bc-429e-bed3-a9a9635f2570.PNG)

![MCMC](https://user-images.githubusercontent.com/66432460/129112213-51168868-c6b8-42fb-adae-16ecc4c4c602.PNG)

OFTI orbit:
![OFTIorbit](https://user-images.githubusercontent.com/66432460/129112465-4b17b984-7af7-4574-8f7c-c29bc72ead96.PNG)

MCMC orbit:
![MCMCorbit](https://user-images.githubusercontent.com/66432460/129112502-150ba8f7-6591-42ff-a76d-c59a391f52ff.PNG)

**Comment by sblunt** [comment]
Hey Rachel, 

I believe this was a plotting bug we fixed in a recent version, but I'm having trouble finding the issue right now. If you update to the latest version does the problem persist?

The conversion message when using OFTI is just because OFTI requires data points to be written as separation/PA in order to perform the scale-and-rotate step. If this is the bug I'm thinking it is, it should only be affecting the plotting of the data points, not the orbit fits themselves. The reason your fits look different right now is because the MCMC is unconverged.

**Comment by sblunt** [comment]
Thanks for the bug report!

**Comment by rbowru** [comment]
Thanks for your reply!  Good to know that it is probably not affecting the orbit fits. 

I tried an update of orbitize yesterday when I noticed this issue, but I don't think it changed anything.  My latest completely fresh installation was from after Code/Astro 2021, around the end of June. 

I went digging into the code a little, and in the sampler.py file in the OFTI class there is a section labeled "# convert RA/Dec rows to sep/PA" that doesn't appear in the MCMC class.  That caught my eye, thinking that step might be missing in MCMC.  At that point, I manually converted the couple of points that were affect between ra/dec and sep/pa using your equations in the system.py file before leaving the code to run overnight and converge.

**Comment by sblunt** [comment]
Ah, ok. Thanks for digging into it! I'm going on vacation for a week, so I'll dig into this more when I get back. Glad to know you have an interim solution working.

**Comment by sblunt** [comment]
@rbowru does PR #262 fix this issue for you?

**Comment by sblunt** [comment]
I tested this a bit and believe it's working on the `main` branch now. @rbowru, feel free to reopen if you're still seeing this issue when running with the code on `main`.
