### ISSUE TITLE
Conversions module necessary?

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#273]
Hey @TirthDS, is the conversions.py module needed? Jason noticed that it isn't being called anywhere. I deleted it on the main brach, but the `conversions-deprecate` still has it in case you need it. If not, feel free to delete that branch.

**Comment by TirthDS** [comment]
Oh I totally forgot about that. The conversions.py file is not needed, but I think it might be worthwhile to move over the ecosw conversions to basis.py eventually.

**Comment by sblunt** [comment]
Sounds good. I'll remove that branch then. Those conversions are pretty straightforward, so we'll worry about it when we get around to implementing the ecosw basis.
