### ISSUE TITLE
Restrict angles to be single peaked

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#28]
Without RVs, imaging astrometry has argument of periastron and longitude of ascending node doubly peaked, with the peaks 180 degrees apart. The distribution is identical between [0,180) and [180,360). Sampling multimodal distributions with MCMC is annoying, so it'd be nice if we had the option to only sample in the [0,180) degree range when we want to be lazy.

Technically, I think this just requires an optional argument and changing the uniform bounds on the angles, so it should not be too hard. 

A stretch goal can be to estimate quickly (via maybe LSQR, or the burn in from MCMC) where the peaks are, and center the sampling around the peak (e.g., [peak-90, peak+90) degrees). This would prevent the edge case that if the peak is centered about zero, you'd still have a multimodal distribution by construction of the prior bounds.

**Comment by semaphoreP** [comment]
Added in PR #31 by @sblunt. Should we add a test for it in the future?

**Comment by sblunt** [comment]
@semaphoreP I just added a few lines of code that automatically check whether a dataset is imaging-only and respond accordingly. Is this the kind of test you mean?

**Comment by semaphoreP** [comment]
Not sure what I meant anymore... I think it was related to writing a pytest for this issue, but I don't know what kind of test I was referring to anymore (doesn't seem like there's a useful one). 

In your update, I think restrict_angle_ranges should have a default of None. If the user sets it to True or False, we should blindly accept it. But if it's none, then do the imaging-only check. Otherwise, the user can't not restrict angle ranges for imaging-only datasets.
