### ISSUE TITLE
correct calculation of difference between two angles

### ISSUE THREAD

**Issue by rjderosa** [sblunt/orbitize#29]
`chi2_lnlike` function should compute the difference between an model (ang1) and observed (ang2) position angle as 

`ang1-ang2 = np.arctan2(np.sin(ang1 - ang2), np.cos(ang1 - ang2))`

so the function will have to be know what the unit of the data is. If it's of type u.rad/u.deg, then it has to use this rather than the simple data-model.

**Comment by semaphoreP** [comment]
Fixed in PR #31 by @sblunt
