### ISSUE TITLE
Need Keplerian orbit solvers

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#3]
I have the code. I need to put it in and make it usable. A stretch goal is to add Rob's eccentricity solver

**Comment by sblunt** [comment]
@devincody I'm assigning this issue to you if you're still interested. 

TODO:
- Modify `kepler.calc_orbit()` so it can take in arrays of orbital parameters.
- Port this version to C, and do some speed tests. Identify when the Python code is faster (probably never, but good to check), and quantify the speed improvements.
- Use `cython` to make the C code work with the rest of our package. The code should attempt to import the C solver, then fall back to the Python version if the import fails.

Things to watch out for:
- Unit conversions are currently done in `kepler.calc_orbit()` using `astropy`. Either write those explicitly into the C code or modify the input requirements in the docs.

**Comment by sblunt** [comment]
I can't seem to assign this issue to @devincody without un-assigning @semaphoreP. Devin, can you assign yourself to this issue?

**Comment by semaphoreP** [comment]
The only thing that may benefit from being written in c is probably the iterative eccentricity solver. The rest (including the part that calls astropy functions) should be just as fast in python. I'm going to close this issue and make the TODOs to make `kepler.calc_orbit()` take in arrays of orbital parameters as well as faster c code into separate issues.
