### ISSUE TITLE
Make sure everything is pickleable and implement multiprocessing for MCMC

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#30]

**Comment by henry-ngo** [comment]
Great! :)

**Comment by semaphoreP** [comment]
Ok, I think tests/test_mcmc.py has the bare-bones code needed to get the MCMC sampler running. Let me know if you have any questions/issues getting it running. If system.py is pickleable, hopefully, it should run parallelized by specifying number of threads when creating the emcee sampler!

**Comment by sblunt** [comment]
Addressed in PR #39.
