### ISSUE TITLE
On the combination of inclination angle and planet mass priors for fits to RV data

### ISSUE THREAD

**Issue by enielsen3522** [sblunt/orbitize#307]
From some work with orbitize! on a fit to RV data, we realized that there can be a surprising result from the combination of the priors on inclination angle and planet mass.

The upshot is that having both a sin(i) inclination prior and a log-uniform mass prior (the orbitize! defaults) effectively imposes a sin^2(i) inclination prior.

If you imagine the RV data is very constraining, then msini is measured very precisely (put another way, m and i are very covariant).  If you make inclination angle smaller, you must make mass larger to compensate.  So if you reduce inclination angle from 90 degrees to 10 degrees, the inclination angle prior tells you that’s less likely by sin(90)/sin(10) = 6.

But you have to hold msini constant to still fit the data, so you have to increase mass by a factor of 6, which thanks to the log-uniform mass prior becomes a factor of 1/6 in your prior.  So your prior penalty for going from 90 degrees to 10 degrees is not 1/6, but 1/36.

I don’t have any deep thoughts about which is correct (indeed, mass of RV giant planets does follow a distribution that’s roughly log-uniform, and from geometry sin(i) is a good inclination angle prior), and there’s the added selection effect of edge-on orbits being preferred for detection…but since I hadn’t thought of it before, I wanted to mention it in case it comes up in other contexts.

**Comment by semaphoreP** [comment]
As discussed offline, it's saying RV planets are more likely to edge on because lower mass planets are more common. Some would call this a feature  😂

**Comment by semaphoreP** [comment]
Closed for now. Re-open when there's more to discuss. Maybe worth going into FAQ if arises again in the future.
