### ISSUE TITLE
when plotting RVs, the median gamma is doubly subtracted

### ISSUE THREAD

**Issue by wbalmer** [sblunt/orbitize#309]
I have a dataset with a big gamma, so this became apparent when I plotted the RV subplot, but there's a double up at line:

https://github.com/sblunt/orbitize/blob/cbbcf9d13aac9c8c88484f2ed61af9b03e3eb961/orbitize/plot.py#L554
https://github.com/sblunt/orbitize/blob/cbbcf9d13aac9c8c88484f2ed61af9b03e3eb961/orbitize/plot.py#L555

where the best fit gamma is subtracted twice from the RV data points to be plotted. commenting out one of the two lines made the plots accurate again :~)

**Comment by sblunt** [comment]
Awesomeeee, thanks for catching this @wbalmer! Do you have time to PR this change? I feel like you should get the credit for changing this line of code.

**Comment by wbalmer** [comment]
will do, once I'm back to work next week :~)

**Comment by sblunt** [comment]
Addressed in PR #318
