### ISSUE TITLE
Hipparcos IAD tutorial - broken links to the beta pic end-to-end code

### ISSUE THREAD

**Issue by rbowru** [sblunt/orbitize#310]
Very minor, but I noticed that there are a couple of broken links in the Hipparcos IAD tutorial.  The blue arrows on the screenshots indicate where the links are broken. 

Thanks again! 

![image](https://user-images.githubusercontent.com/66432460/149397158-8522ebe6-0e8b-4abd-b98c-d923e8794517.png)
![image](https://user-images.githubusercontent.com/66432460/149397172-117040b9-7c07-4d8f-8cd9-6b3d084053ee.png)

**Comment by sblunt** [comment]
Thanks Rachel!! Addressed in commit 76ced1f124cd5b3ad67e8558217eb90a091a3032.
