### ISSUE TITLE
Advanced plotting tutorial errorbar example code not good for datasets containing RV points 

### ISSUE THREAD

**Issue by rbowru** [sblunt/orbitize#311]
version: 2.0.0
computer type: linux

I've discovered that the example code in the "advanced plotting" tutorial doesn't work perfectly for the orbit plot if you apply it to a dataset with RV.  In the example where it's shown how to add errorbars, the sep and pa get pulled from 'quant1' and 'quant2'.  When you have RV data, quant1 is the measured RV (rather than the separation).

There may also be an issue for users with a mix of PA and Sep vs RA and Dec with the relative astrometry data. Here's a screenshot of my data_tab, so you can see what I mean.

Thank you again! 

![image](https://user-images.githubusercontent.com/66432460/150442857-4a906663-1c26-418f-9668-8fe1ccd3dc5e.png)

![image](https://user-images.githubusercontent.com/66432460/150442839-37c2ed79-1d2d-4b4d-a599-64e3a97b8be0.png)

![image](https://user-images.githubusercontent.com/66432460/150442872-0dded59e-19ca-4eb0-be9c-d65187533ef4.png)

**Comment by sblunt** [comment]
Automated error bar plotting added in PR #318, and this part of the tutorial has been removed.

**Comment by sblunt** [comment]
Addressed in PR #318.
