### ISSUE TITLE
Make HIP_IAD MCMC more accessible without internet  

### ISSUE THREAD

**Issue by rbowru** [sblunt/orbitize#313]
Would it be possible to reduce the amount that the HIP_IAD code requires access to the internet? 

I've run into a few challenges running the bit of the Hipparcos/Gaia module that requires accessing the internet for a brief moment when setting up the MCMC.   The laptop I use to run orbitize can only access the internet when plugged into an ethernet port, so it adds an extra complication for starting the MCMC when I work from home or am traveling. In the other case, I was trying to use a computing cluster with fancy firewall protections and it was having trouble getting through the step that required internet access.   While these issues feel niche to my setup, I imagine other users may face the same problem from time to time.  Would it be easy to remove that step that requires internet access? Or make an alternative where users can download an extra file as they are setting up the .d files?

Thank you again!

**Comment by sblunt** [comment]
Definitely, great idea.

**Comment by sblunt** [comment]
PR #319

**Comment by sblunt** [comment]
Addressed in PR #319. Reopen if needed.
