### ISSUE TITLE
Problem reading epoch in the input file. Epoch should be given in MJD

### ISSUE THREAD

**Issue by AlessioPop** [sblunt/orbitize#329]
**reading epoch in the input file raises errors**

I used the same Data provided by the documentation. If I mark the provided Data (MJD) with # in the CSV file I get an empty Table (see Image below).

 
![helpYOU](https://user-images.githubusercontent.com/120112894/213755632-d7de5e04-52df-49cc-b135-a70bc527e676.PNG)

Meaning that the path to the file is working properly. However, when using the provided Data (MJD) I get the following error: 

![helpihelpi](https://user-images.githubusercontent.com/120112894/213754729-9b37760b-bd9e-46b4-a1aa-ef90817edf17.PNG)

**My System:**
 - OS: Linux
 - orbitize! Version 2.1.2

**Comment by AlessioPop** [comment]
orbitize does not support the latest version of numpy, so one should downgrade to an older version of numpy to solve the issue.

**Comment by sblunt** [comment]
Thanks for the bug report!

Addressed in PR #331. Thanks @tomasstolker!
