### ISSUE TITLE
Float function of NumPy does not exist?

### ISSUE THREAD

**Issue by tomasstolker** [sblunt/orbitize#330]
This line:
https://github.com/sblunt/orbitize/blob/910d4065e4ff702d076426c9ddf64b3504631f6a/orbitize/read_input.py#L237

Causes the following error with my installation:
`AttributeError: module 'numpy' has no attribute 'float'`

I think because `numpy.float` does not seem to exist:
https://numpy.org/doc/stable/user/basics.types.html

Perhaps using `numpy.float_` solves it? Or maybe using `numpy.array` and then check the `dtype` afterwards (instead of using the `try`-`except`).

**Comment by tomasstolker** [comment]
I think that this issue is about the same error actually: #329

**Comment by tomasstolker** [comment]
The problem is related to `numpy` version 1.24 (`np.float` was deprecated). Downgrading to version 1.23 solved the issue!

**Comment by sblunt** [comment]
Addressed in PR #331. Thanks @tomasstolker!
