### ISSUE TITLE
Standard to XYZ documentation needs a minor fix

### ISSUE THREAD

**Issue by michaelkmpoon** [sblunt/orbitize#347]
**Describe the bug**
I think orbitize.basis.XYZ.standard_to_xyz has some incorrect documentation. To convert from standard orbital elements to XYZ for more than 1 set of parameters, the documentation says that the first dimension must be the number of orbital parameter sets. 

![image](https://github.com/sblunt/orbitize/assets/35639046/912e8916-9f4e-4d9b-a09d-40117ebf78a7)

**To Reproduce**
Here is a simple example that shows the error, as well as the how instead I got it to work (by transposing the array). Instead, it should be the second dimension that is the number of orbital parameter sets.

![image](https://github.com/sblunt/orbitize/assets/35639046/3de0a29c-f8e5-4e5f-9804-08d752577163)

This is with orbitize! Version 2.2.2.

**Comment by sblunt** [comment]
Addressed in #363.
