### ISSUE TITLE
Unclear which mass to specify for fitting two planets with astrometry

### ISSUE THREAD

**Issue by bailer-jones** [sblunt/orbitize#358]
It is not clear to me from the documentation or code which mass I should specify (stellar or system) for the configuration specified in issue 357, namely

    sys = system.System(num_secondary_bodies=2, 
                    use_rebound=True, 
                    fit_secondary_mass=True,
                    data_table=dat, 
                    tau_ref_epoch=timeref,
                    stellar_or_system_mass=mass_star/msun, mass_err=0, 
                    plx=1.0, plx_err=0.0) 

In
https://orbitize.readthedocs.io/en/latest/system.html
it states: 
"stellar_or_system_mass (float) – mass of the primary star (if fitting
for dynamical masses of both components) or total system mass (if
fitting using relative astrometry only) [M_sol]"
However, this is not unambiguous to me, because "fitting for both components" and 
"using relative astrometry" are not mutually exclusive.
When solving for one planet using relative astrometry, then I understand we give the total system mass (which makes sense).
But if we have relative astrometry on one or more planets and are fitting their masses, which mass do we specify in system.System() above? (I my particular case I need to "fit" for the masses, even though I may keep them constant, as I need to include the perturbing effect of one on the other. I also only provide data for one planet, but that should not be relevant.)

**Comment by sblunt** [comment]
Good point, and thanks for raising this issue! In general, if you're fitting for the dynamical masses of the planets, `stellar_or_system_mass` refers to the mass of the primary star (not the total mass). I'll amend the documentation in the docstring you referenced.

**Comment by bailer-jones** [comment]
Thanks for the clarification :-)

**Comment by sblunt** [comment]
Addressed in #363
