### ISSUE TITLE
PTMCMCSampler: View / chop MCMC chain and update Results object

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#37]
From #35 

>Add a function in the MCMC sampler to inspect the MCMC chains (either visually or by some metrics) and allow the user to chop off additional steps as "burn-in" if part of the MCMC chain hasn't converged yet. Update the results object with the updated chain.

To be completed after multi-threaded MCMC is complete (#30)

**Comment by henry-ngo** [comment]
Updating with notes from Slack last month.

Plotting the posteriors should be in Results and generic. Walker examination is something only MCMC would do so plotting that in Sampler makes sense.

For PTMCMC, the user could create a Results object for each temperature they care about. I'll have a separate "create_results" or something like that method in the PTMCMC and EnsembleMCMC classes that treat their specific behaviour/output separately but will end up creating a generic Results object

**Comment by henry-ngo** [comment]
I got the first part (view chains) done during the Hackathon (thanks for organizing!) but the second part and tests will come later as I find time over the next few weeks. 

One question on how we want to implement "chopping". The simplest way (and what I originally envisioned) was to actually delete the "chopped" regions so that removing the first X steps (or whatever) is permanent. 

But if there is strong demand for reversible chopping, we can use masked arrays or store the chopped bits elsewhere and keep track of what's included/not included. There are potential complications since many other routines now use Results objects without considering that they might be masked arrays (we can handle this by having the main attributes contain only values the user has kept). Anyways, my thought was that we don't need to implement this "reversible chopping" option right now and just be clear in the docstring that this is a permanent change. Users who want to change their mind can always save a copy of the Results object and reload it if they want to undo a chop. But wanted to hear any potential other opinions!

**Comment by sblunt** [comment]
Thanks @henry-ngo! I think we can safely delete the burn-in once the user gives the OK. That's basically what we're doing now, just without user input, right?

**Comment by henry-ngo** [comment]
Okay! Currently, the number of burn-in steps is a parameter users can set when they call `run_sampler` and those steps are just deleted.

**Comment by sblunt** [comment]
Cool. Yeah I think just deleting them is good!
On a side note, we should make sure there is an option *not* to view the chains e.g. if users want to run MCMC overnight with a predefined # of burn-in steps.

**Comment by henry-ngo** [comment]
My current implementation plan is to add two new methods to the MCMC `Sampler` class:

`examine_chains()` will display plot(s) of the walker positions as a function of step, one plot per parameter

`chop_chains()` will take the number of steps from the beginning to chop and it will modify the chain stored in that `sampler` object and also update the corresponding `Results` object to remove the same steps. I haven't written this method yet so I will have to decide whether I would just remove all samples in the current results object and add new ones or if I will just delete the current results object and make a new one. 

So, all existing code won't do anything differently. If a user wants to inspect and examine/chop the chains, they will need to call these methods after running the MCMC. I suppose that we can also add an option in the `run_sampler` method to automatically call `examine_chains` after the MCMC runs as a convenience!

**Comment by sblunt** [comment]
I see. Sounds great!

**Comment by henry-ngo** [comment]
The branch `view_chop_chains` now implements these features! It is also passing tests.

Small note on a change to the original plan: The MCMC Sampler object has attributes storing the chain, likelihoods, etc. These are saved and added to the Results object attached to the Sampler object at the end of each call to `run_sampler`. My original plan was to update both these objects as well as the `Results` object.

However, I realised that the attributes that is part of the MCMC sampler object only contains the value of the most recent call to `run_sampler`. So if you get 10,000 orbits by calling `run_sampler` twice, you only have the last 5000 orbits in `sampler.chain` for example. 

Therefore, this function now only modifies what is saved in the `Results` object. This is the intention of our API anyways, I believe: in our tutorials we always get the samples from `Results` object. 

There are two outstanding things to do before I create a PR for these features:

1. Wait for PR #126 to resolve on whether we will save likelihood, posteriors, or both to `Results`. At the moment, this branch assumes the current version of #126 will stand (i.e. only save likelihoods). I'll change it if PR#126 changes and I will also wait for #126 to merge first so that I can resolve any conflicts.

2. Write tutorials for these two new features and ensure current tutorials only use results from the `results` object.

I'm going to put this branch aside for awhile to work on other things and to wait for #126 to resolve. I'll check back in a week or so :)

**Comment by sblunt** [comment]
Addressed in PR #139
