### ISSUE TITLE
Parallax in mas vs arcseconds

### ISSUE THREAD

**Issue by logan-pearce** [sblunt/orbitize#38]
driver.py takes parallax in arcseconds, while kepler.calc_orbit takes parallax input in mas.  Which one should be the standard?

**Comment by sblunt** [comment]
We should believe `kepler.calc_orbit`. @logan-pearce, feel free to fix this in `driver.py`, or let me know and I can fix it.

**Comment by semaphoreP** [comment]
We determined @sblunt was going to do this quick fix in `driver.py`

**Comment by sblunt** [comment]
Addressed in commit 4c789b1627f7c0ff3f5431a8fb947c6409f62598.
