### ISSUE TITLE
Slightly inaccuracies in Hipparcos IAD reconstruction for very high PM, high RV stars

### ISSUE THREAD

**Issue by sefffal** [sblunt/orbitize#383]
**Describe the bug**

This is a relatively minor effect even on very high proper motion stars. But I think it is still worth sharing my findings and possibly documenting.

The Hipparcos IAD from the van Leeuwen reduction (e.g. Java tool) are not perfectly reconstructed or refit for very high proper motion, very high RV stars. As far as I can tell, HTOF and orvara also share this limitation.

After way too much time spent digging into this, it seems that the van Leeuwan reduction considered a non-linear model when they fit 5-parameter solutions to account for high proper motion. Actually, I think they did this by fitting their linear model on the residuals iteratively, just like Gaia.
At the same time, they ignored non-linearities from high RV stars, despite previous reductions (1997) considering these effects (Table 1.2.3 from the 1997 book, vol 1). 

So to get a perfect re-construction of the van Leeuwen hipparcos IAD on high PM, high RV stars like Kapteyn's star (HIP24186), the 5-param model should consider this curvature but ignore RV. This allows the IAD to be re-fit and exactly match the catalog values, which currently fails on this star.

Then, when actually fitting the data, the non-linear effects of the RV should be included so as not to bias the planet parameters. 

Here is a full grid of comparisons I did using a test code that considers the impact of these non-linear effects during the reconstruction and during the fitting:
```
model                                    | σ-agreement with Hipparcos | max posterior log density
-----------------------------------------|----------------------------|--------------------------
non-lin  no-rv recon, non-lin yes-rv fit | 0.061                      | -357.029 (best residuals)
non-lin  no-rv recon, non-lin  no-rv fit | 0.00073     (best match)   | -357.538
non-lin yes-rv recon, non-lin yes-rv fit | 0.00125                    | -357.539
    lin  no-rv recon,     lin  no-rv fit | 0.00090                    | -357.536
```
So in summary, while reconstructing the van Leeuwan residuals:
* include non-linearities from spherical coordinates but always assume 0 RV.
* To exactly re-fit the solution, include non-linearities from spherical coordinates and assume 0 RV.
* To improve the fit to the data slightly, include non-linearities from spherical coordinates and use the star's actual RV.

In the case of HIP24186, Kapteyn's Star, this is a delta-chi^2 of 0.51, which is a non-negligible improvement to the fit.

**To Reproduce**
Steps to reproduce the behaviour:

~Perform the `nielsen_iad_refitting_test` on an extremely high PM star. I tested with Eps Indi, but I think it will show up even more for Kapteyn's star.~
Edit: I actually can't see any detectable deviation in the plots, since it's such a small effect. But looking at the code, I still think it's impacted. As I said, it's a very small effect.

**Expected behavior**
The IAD will be perfectly refit.

**Comment by sefffal** [comment]
You know what, I'm not sure about this --- there might be something else going on besides the linear/non linear stuff. I'm going to close for now, and I'll reopen if I can get to the bottom of it. Sorry for the issue spam.

**Comment by sblunt** [comment]
No worries! Thanks for documenting your thought process.
