### ISSUE TITLE
Implement OFTI sampler

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#4]
Get it working for 1 planet with only imaging data.

**Comment by sblunt** [comment]
@logan-pearce: see skeleton code in sampler.py. For now, focus on filling in the basic stuff (no speedups yet). Let me know if you'd like to split up the work in any way.

**Comment by logan-pearce** [comment]
Thanks!  I will work on this and let you know if I have questions.

**Comment by sblunt** [comment]
Incorporated in PR #48! Yay! Thanks @isabelangelo and @logan-pearce for your work on this!
