### ISSUE TITLE
Ordering of results posterior sample array (results.Results.post)

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#49]
The API (written by @Sarah Blunt) specifies that the posterior sample array (or orbits) is a 2D array with shape (num_parameters, num_samples)

However, for MCMC output and input to corner etc. the 2D posterior sample array usually has shape (num_samples,num_parameters).

For now, I will proceed with the MCMC and corner.py standard but if OFTI is already implemented the opposite way, we can switch or discuss which way we should go. 

One other reason to choose the MCMC/corner.py way (num_samples,num_parameters) is that in numpy, a 2-D array with shape (M,N) has M rows and N columns. So basically, it is a set of M arrays that each of length N. If M = num_samples and N=num_parameters, then each of the M arrays is a complete orbit on its own, whether computed by OFTI or MCMC. So MxN means M orbits each with N parameters, which makes more intuitive sense to me!

**Comment by sblunt** [comment]
@isabelangelo can you confirm that OFTI results are being sent this way?

**Comment by isabelangelo** [comment]
It looks like run_sampler outputs an array of accepted orbits that is (num_samples X 8), so I think it should be working!

**Comment by henry-ngo** [comment]
Great :)
