### ISSUE TITLE
Custom tau start date

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#62]
Somewhat related to #61. We should have an option for a user defined start date for tau (currently it's starting from MJD=0). There is possible evidence that having tau near the date of current observations helps with MCMC convergence.

**Comment by semaphoreP** [comment]
So in discussions, we determined that tau is degenerate with period (as one might expect), so having tau start too far away from the actual observations creates weird covariances that are not Gaussian, and thus hard to sample. 

So, what should be the default? MJD=0 is too far back in time compared to most of our data. MJD=first astrometry data makes dataset dependent and possibly too confusing. My current suggestion is MJD=60000 (Feb 25, 2023), which is a nice round number close in time to our current data. Of course, we should have the option for the user to have a custom start date for tau.

**Comment by henry-ngo** [comment]
How far away is "too far away"? Since most observations using orbitize will probably be from 2010 onwards, a date like 2023 is great if within ~10-20 years is close enough so that the default value will be good for as long as python is likely to be dominant in astronomy ;)

But if 10 years is already "too far away" then I'd prefer a date closer to today and no need to favour a nice round MJD.

**Comment by sblunt** [comment]
I'm in favor of MJD=60000! I think we should use the same MJD convention for everything, including input astrometry. Because of that, I think we should make this a V1.0 issue. @semaphoreP would it be possible to do an MCMC run with beta Pic and MJD= 60000 to make sure it's not "too far away?"

**Comment by sblunt** [comment]
Oh wait I'm stupid never mind about the v1.0 issue, I didn't think that comment through. But I still agree with my suggestion to do an MCMC run with MJD=60000!

**Comment by semaphoreP** [comment]
Implemented in PR #105
