### ISSUE TITLE
Add Kosmo O'Neil priors to priors.py

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#63]
See https://arxiv.org/pdf/1809.05490.pdf, awesome work by K. Kosmo O'Neil. Would be great to have these priors as options in `orbitize`!

**Comment by sblunt** [comment]
A first-draft version of this feature for MCMC only is implemented in the `obs-priors` branch. Summary of game plan for OFTI incorporation that came out of discussion with Greg Martinez & Kelly Kosmo today:
- use rejection sampling to generate samples from the ObsPrior. Proposal distributions: log-uniform in P, uniform in e
- rotate Omega but don't scale sma

**Comment by sblunt** [comment]
The Jacobian currently implemented on the `obs-priors` branch isn't correct, since we're using a sma basis, and the Jacobian in Kelly's paper involves partial derivatives assuming we fit in a per basis. I need to calculate and implement the correct Jacobian.

**Comment by sblunt** [comment]
@isabelangelo I just merged the changes from `main` into my `obs-priors` branch, if you want to check out what I've coded up so far for this. As I understand it now, the remaining TODOs are:

- derive the analytical form for the standard orbitize basis
- update the code (potentially change the way I initially coded it to be consistent with the newer API)
- test & document
- (potentially): expand to other bases

Feel free to use the code I have as a starting point or to completely start over (I won't be offended either way).

**Comment by isabelangelo** [comment]
Thanks Sarah this is super helpful :) I'll look over it and see how much of the code we want to incorporate, but regardless it's good to have for reference!

**Comment by sblunt** [comment]
It's been 84 years, but finally this issue will be addressed in PR #365!

**Comment by sblunt** [comment]
Addressed!!!
