### ISSUE TITLE
MCMC return autocorrelation time

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#79]
Related to issue #37. We should have some approved tools for assessing convergence of MCMC walkers, since it is probably the trickiest part of MCMC orbit fitting. Similarly, we should expand the MCMC tutorial. 

- [ ] function that returns the autocorrelation time of the chains
- [ ] documentation in the MCMC tutorial on how to use the above feature to assess convergence

**Comment by zhexingli** [comment]
Is mcmc convergence criteria now incorporated into orbitize? Just being curious

**Comment by semaphoreP** [comment]
Not yet, but check out section 2.3.2 of the orbitize! paper for a summary of how we assess convergence: https://arxiv.org/abs/1910.01756

**Comment by sblunt** [comment]
More discussion added to MCMC tutorial in PR #79

**Comment by sblunt** [comment]
Further discussion added in PR #346. Closing this now; feel free to reopen if more functionality is desired.
