### ISSUE TITLE
`Driver` should accept both properly inputted .csv files and `astropy.table.Table` objects

### ISSUE THREAD

**Issue by sblunt** [sblunt/orbitize#80]
Currently, `Driver` expects a csv. We should make it flexible enough to accept either a csv or an `astropy.table.Table`. Thanks @logan-pearce for the suggestion!

**Comment by henry-ngo** [comment]
`read_input.py` provides two possible read modes: 

`read_formatted_file` reads a CSV file that must be formatted with certain columns, typically values used by observers (e.g. delta RA/DEC, sep/pa, RV) and then generalizes this to a generic `orbitize` style.

`read_orbitize_input` reads any file with the generic `orbitize` style

`Driver` currently only uses `read_formatted_file`. To improve this, we should also allow it to use `read_orbitize_input` which would allow reading in of other filetypes created by `orbitize` as well. 

Reading in an `astropy.table.Table` directly could work too. The original intent of `read_orbitize_input` was to allow the user to use `write_orbitize_input` (another method of `read_input.py`) to save an `astropy.table.Table` to a file and then re-read it later. But allowing a shortcut makes sense too

**Comment by sblunt** [comment]
Addressed in PR #82. Check it out, @logan-pearce!

**Comment by logan-pearce** [comment]
Nice!  I like this feature, not having to write out a new file.  Great work.
