### ISSUE TITLE
Sampler.OFTI changes ra/dec input to sep/pa but `quant_type` remains "radec"

### ISSUE THREAD

**Issue by henry-ngo** [sblunt/orbitize#83]
This bug was causing a bunch of my unit tests on Driver to fail when I was testing for the ability to accept either a filename or an astropy.table.Table object.

When a Driver object is created with the OFTI algorithm, initializing the Sampler.OFTI object will convert all of the ra/dec input to sep/pa. This changes the `quant1`, `quant1_err`, `quant2`, and `quant2_err` values. However, it does not change the last column, which is `quant_type`. That entry remains `radec`. 

This causes problems when I (or another user) tries to access the data table through the `sampler.data_table` attribute because the wrong information was shown. 

There three potential fixes:

1. Add one line to the for-loop where the ra/dec values are being converted to also change this last column (from 'radec' to 'seppa'). So, accessing the data_table at any time will provide consistent values, however, it will not be the same as the input (i.e. you get the table used to by OFTI but not the input table for troubleshooting). 

2. Change lines 97-100 of sampler.py (where astropy.table columns are being assigned to local attributes) to be *copying* the values instead of just assignment. Since Table objects are passed by reference, not by value, when the variables to which these columns were assigned are changed later, it changes the original too. In addition, with this solution, we would have two separate tables stored for the sampler object: `input_table` showing the original input and `data_table` for showing the values used by OFTI to calculate. 

3. Do the copying thing as in option 2, but do not expose the `data_table` at all to users to keep it behind the scenes.

I personally like option 2 best but option 3 also makes sense if you want to keep it under the hood. I can implement any of these but it would be good to discuss ideas.

**Comment by sblunt** [comment]
Thanks for catching this bug, @henry-ngo! I like option 2 best as well.

**Comment by semaphoreP** [comment]
Option 2 sounds good to me too. I would suggest printing a message so that the user knows this is happening behind the scenes . This is just related to the OFTI sampler right?

**Comment by henry-ngo** [comment]
Yes, this is only for the OFTI sampler.

**Comment by isabelangelo** [comment]
I think option 2 sounds good as well. I'll work on this and add a print statement as Jason suggested. Thanks for the input Henry!

**Comment by isabelangelo** [comment]
This issue should be fixed now! I took Henry's suggestion and made it so sampler creates variables from copies of the original data table, so self.system.data_table will be constant. 

Additionally, as we discussed, I made it so that OFTI has two distinct table attributes: self.input_table (same as self.system.data_table, identical to original file) and self.data_table (table that is used for OFTI analysis).

I ran it on my original test_OFTI.py and it passed :)

**Comment by henry-ngo** [comment]
Yay!

**Comment by sblunt** [comment]
Looks good! Create a PR whenever you're ready. :)

**Comment by isabelangelo** [comment]
See PR#98

**Comment by sblunt** [comment]
Fixed in issue #98, as referenced above.
