### ISSUE TITLE
Custom likelihood functionality

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#87]
Sometimes we have measurements that don't fit the standard orbitize format yet (e.g., Gaia/Hipparcos astrometry), and it would be nice to fit it as a one-off before making it a full feature (in case the format is supposed to change). It would be nice to be able to pass into the system(?) object, an extra likelihood function that is custom by the user. It should take a 2-D array of fit parameters, and return an array of likelihood values.

**Comment by sblunt** [comment]
Addressed in commit #4ea24988af185373e02dc78a59c480301e6c5acd
