### ISSUE TITLE
Jupyter Lab Rendering

### ISSUE THREAD

**Issue by malenarice** [sblunt/orbitize#88]
When running OFTI in Jupyter Lab, the progress bar creates many empty spaces instead of augmenting numerically.

(occurs for the following lines:)

s = myDriver.sampler
orbits = s.run_sampler(1000)

**Comment by isabelangelo** [comment]
I looked into this, and it's actually a bug in jupyter lab- they're unable to handle "\r" carriage returns. It looks like they're working on this, and I commented on one of their issues in github as well. But for now I think we can only wait until they fix it :/

**Comment by semaphoreP** [comment]
Alright, it seems outside of the scope of orbitize, so I'm going to close this issue. Thanks for investigating, and following up with the developers @isabelangelo!
