### ISSUE TITLE
N-body orbit solver

### ISSUE THREAD

**Issue by semaphoreP** [sblunt/orbitize#93]
In the future, in particular for multi-planet systems, it could be nice to use an N-body integrator (like `rebound`) to solve for the planets' positions. An N-body integrator can account for planet-planet interactions. This is not a pressing issue, so we can deal with it down the line.

**Comment by hannorein** [comment]
PSA: I'm happy to help out if you ever want to make orbitize talk to rebound.

**Comment by sblunt** [comment]
Thanks @hannorein! @sofiacovarrubias has been doing some excellent work on this issue as an undergrad research project. We'll keep you updated!

**Comment by sblunt** [comment]
Merged into develop in PR #254! Incredible work @sofiacovarrubias!

**Comment by sblunt** [comment]
Merged into main in PR #270
